### Recuperar peliculastodas las peliculas
GET http://localhost:1234/movies

###Recuperar una pelicula por ID
GET http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

### Recueprar todas las peliculas de un género
GET http://localhost:1234/movies?genre=ACTION

### Recueprar todas las peliculas de una palabra del titulo
GET http://localhost:1234/movies?title=Godfather

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1990,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://www.imdb.com/title/tt0068646/mediaviewer/rm4263220224",
    "genre": [ "Action",
                "Crime",
                "Drama"
                 ]
}

### Actualizar una pelicula
PATCH http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08   
Content-Type: application/json

{
    "year": 2011,
    "duration": "180 minutos"
}

